version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test4Project
  gitServerName: sbnew
  gitUrl: https://github.com/sbudhira
  gitUsername: sbudhira
  gitBranch: main
- name: Test20Project
  gitServerName: sbnew
  gitUrl: https://github.com/sbudhira
  gitUsername: sbudhira
  gitBranch: main
services:
- serviceName: project.test4.integrations:fs4
  packages:
  - name: Test4Project
    version: "1.0"
- serviceName: pub.alert:channels
  packages:
  - name: WmPublic
    version: 11.1.0.0.2032
